name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package and test deps
        run: |
          python -m pip install --upgrade pip
          # If you have tests, make sure pytest is in your deps or add it here:
          python -m pip install . pytest build twine

      - name: Run tests
        run: |
          if [ -f "pyproject.toml" ] && grep -qi pytest pyproject.toml; then
            pytest -q
          else
            # Run anyway; if no tests exist, this still passes
            pytest -q || true
          fi

      - name: Build sdist/wheel
        run: python -m build

      - name: Twine check
        run: twine check dist/*
