name: Publish to PyPI

on:
  push:
    tags:
      - "v0.1.0"  

permissions:
  id-token: write  
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/pyasyncbtrack/
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build
        run: |
          python -m pip install --upgrade pip build
          python -m build

      - name: Twine check
        run: python -m pip install twine && twine check dist/*

      - name: Publish to PyPI (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
